# -*- coding: utf-8 -*-
"""Frequencia_fundamental.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t0gl8jKYNWnVi08Wg3O9Gdd7b--RhBIT
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

caminho = '/content/drive/MyDrive/Valdemar/Data_acquisition_code/Aquisicao_certo/Testes/Aceleracao/ac'
nome_coluna = ['Tempo', 'Aceleração']

dados = pd.read_csv(caminho, header= None, names = nome_coluna, delimiter = '\t')


dados['Aceleração'] = dados['Aceleração'].astype(str).str.replace(',', '.').astype(float)

dados['Tempo'] = dados['Tempo'].astype(str).str.replace(',', '.').astype(float)

dados.head()

import numpy as np

def calcular_frequencia_fundamental(aceleracao, taxa_amostragem):
    # Aplicando a Transformada Rápida de Fourier (FFT) nos dados de aceleração
    fft_resultado = np.fft.fft(aceleracao)

    # Calculando o espectro de frequência
    espectro = np.abs(fft_resultado)

    # Encontrando o índice da frequência fundamental
    indice_f0 = np.argmax(espectro[1:]) + 1  # Ignorando a componente DC (0 Hz)

    # Calculando a frequência fundamental em Hz
    f0 = (indice_f0 / len(aceleracao)) * taxa_amostragem

    return f0


# Frequência de amostragem em Hz
taxa_amostragem = 2000  # Exemplo: amostragem a cada 1 milissegundo (1000 Hz)


# Calculando a frequência fundamental
f0 = calcular_frequencia_fundamental(dados['Aceleração'], taxa_amostragem)

print("Frequência Fundamental (f0):", f0, "Hz")
